### ISSUE TITLE
Unable to Handle "Save As" Dialog Box when Exporting Table Data to Excel

### ISSUE THREAD

**Issue by harishgajawada** [gutskodv/PySapGUI#1]
When exporting table data to Excel using the "Export to Spreadsheet" functionality (Ctrl+Shift+F7) in our SAP system, I encounter a problem with the "Save As" dialog box. After selecting the desired output format as XLSX from the dropdown and pressing Enter, the "Save As" window dialog box appears. However, I'm unable to send keys or interact with this window programmatically.

Additional Information:

The code used to handle other SAP windows and dialogs is functioning correctly.
I have tried using VBA's SendKeys method and the pyautogui library in Python, but both have failed to interact with the "Save As" dialog box.
The SAP GUI Scripting is enabled and configured correctly in the SAP environment.
Please provide guidance on how to programmatically interact with the "Save As" dialog box in order to automate the file name and path selection during the export process.

Thank you for your assistance.

**Comment by gutskodv** [comment]
I know such limitations. I suggese to use alternative ways how to save table. 
For instance, I ve just added new feature to my project - transaction SE16 (transaction_se16.py).
It allows you to save table content to file.
